### ISSUE TITLE
Packaging for Qt?

### ISSUE THREAD

**Issue by gnuherdnix** [o3de/3p-package-source#21]
Hi there,

I'm aware that o3de uses a patched Qt 5.15 version which gets downloaded as a binary artifact. Is it also packaged as part of this repository? I haven't found out how to rebuild it from source locally, with the o3de patches.

**Comment by lawsonamzn** [comment]
We're working on it.  The actual full source is downloadable right now, the LICENSE/README files at the root of the o3de distro has a link to where the src package can be downloaded.

**Comment by cgalvan** [comment]
I have started the process now of bringing all our patches into a public for of Qt5, here is the issue tracking for it (https://github.com/o3de/o3de/issues/3333)

It will be available here:

https://github.com/o3de/qt5/tree/5.15.1-az

**Comment by gnuherdnix** [comment]
Hi @cgalvan , I'm sure this is likely still in progress, but I'm looking to hack on some of the Qt Components a bit and wanted a locally-built version of Qt. I see in the root: `package_build_list_host_<PLATFORM>.json`, that there is reference made to build Qt: `"qt-5.15.2-rev4-windows": "package-system/qt-windows",`. Could you share some notes on how this is done now so I can attempt it locally? Right now, I can build from the Qt branch, but it's not picked up by the 3rdParty cmake package resolver. Looking at the built sources that get pulled down, there seems to be a `FindQt` helper that's created at some point.
