### ISSUE TITLE
qt?

### ISSUE THREAD

**Issue by spotaws** [o3de/3p-package-source#57]
For a Fedora native build, we need to rebuild the o3de patched qt from source (the prebuilt binaries link to Ubuntu specific files that do not exist at that version on Fedora). It would be extremely helpful if you could provide the same sort of tooling for qt in this repo.

**Comment by cgalvan** [comment]
I've just put up a PR for bringing over our Qt build scripts into the package source system:

https://github.com/o3de/3p-package-source/pull/58

I haven't gotten a chance to fully test it on Linux yet, but it should get you started.

**Comment by cgalvan** [comment]
The build scripts for all platforms has been merged in here:  https://github.com/o3de/3p-package-source/pull/58
